apiVersion: v1
kind: Service
metadata:
  name: classificacao-service
spec:
  #porta externa, acessivel fora do cluster
  type: NodePort
  selector:
    app: classificacao
  ports:
    - name: classificacao
      protocol: TCP
      port: 7000
      targetPort: 7000