apiVersion: apps/v1
kind: Deployment
metadata:
  name: consulta-deployment
spec:
  #quantas cópias
  replicas: 1
  selector:
    matchLabels:
      app: consulta
  template:
    metadata:
      labels:
        app: consulta
    spec:
      containers:
      - name: consulta
        image: coutelas/ecm516-20232-consulta
        resources:
          limits:
            memory: 256Mi
            cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: consulta-clusterip-service
spec:
  selector:
    app: consulta
  type: ClusterIP #se não colocar vai ele pq é padrão
  ports:
    - name: consulta
      protocol: TCP
      port: 6000
      targetPort: 6000