apiVersion: apps/v1
kind: Deployment
metadata:
  name: observacoes-deployment
spec:
  #quantas cópias
  replicas: 1
  selector:
    matchLabels:
      app: observacoes
  template:
    metadata:
      labels:
        app: observacoes
    spec:
      containers:
      - name: observacoes
        image: coutelas/ecm516-20232-observacoes
        resources:
          limits:
            memory: 256Mi
            cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: observacoes-clusterip-service
spec:
  selector:
    app: observacoes
  type: ClusterIP #se não colocar vai ele pq é padrão
  ports:
    - name: observacoes
      protocol: TCP
      port: 5000
      targetPort: 5000